language : csharp
script: bash scripts/deploy.sh
dotnet: 4.6.1

deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_API_KEY
    keep_history: false
    on:
        branch: master