language : generic


deploy:
    provider: script
    script: bash scripts/deploy.sh
    on:
      branch: master
  
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_API_KEY
    keep_history: false
    on:
        branch: master