language : generic
script: bash scripts/deploy.sh

addons:
  homebrew:
    packages: docfx

deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_API_KEY
    keep_history: false
    on:
        branch: master